const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const {test}=require('node:test');
const {webcrypto}=require('node:crypto');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
const source=html.match(/<script id="core">([\s\S]*?)<\/script>/)[1];
const context=vm.createContext({crypto:webcrypto,structuredClone,Date});
vm.runInContext(source+';globalThis.core=VisitorPassCore;',context);
const core=context.core;
function fixture(options={}){let who={role:'Visitor',hostId:'admissions'},seq=0,date='2026-10-03';const events=[];const repository=core.createMemoryRepository();const service=core.createService({repository,actor:()=>who,today:()=>date,id:()=>String(++seq),audit:e=>events.push(e),...options});return {service,repository,events,role:(role,hostId='admissions')=>{who={role,hostId};},date:d=>{date=d;},input:{name:'Alex Morgan',date:'2026-10-03',host:'admissions'}};}
test('visitor creates a pending request without a code',()=>{const f=fixture();const r=f.service.request(f.input);assert.equal(r.status,'pending');assert.equal(r.code,null);});
test('blank and markup names are rejected',()=>{const f=fixture();for(const name of ['', 'A', '<script>alert(1)</script>'])assert.throws(()=>f.service.request({...f.input,name}));assert.equal(f.repository.all().length,0);});
test('Unicode names and apostrophes work',()=>{const f=fixture();assert.equal(f.service.request({...f.input,name:'  Émilie O’Connor  '}).name,'Émilie O’Connor');});
test('bad dates and past dates are rejected',()=>{const f=fixture();for(const date of ['2026-02-30','2026-10-02','nonsense',''])assert.throws(()=>f.service.request({...f.input,date}));});
test('unlisted hosts are rejected',()=>{const f=fixture();assert.throws(()=>f.service.request({...f.input,host:'unknown'}));assert.throws(()=>f.service.request({...f.input,host:'toString'}));});
test('Visitor and Guard cannot approve at the service boundary',()=>{const f=fixture();const r=f.service.request(f.input);for(const role of ['Visitor','Guard']){f.role(role);assert.throws(()=>f.service.decide(r.id,'approved'),/only Host/);}assert.equal(f.repository.get(r.id).status,'pending');assert.equal(f.repository.get(r.id).code,null);});
test('only the assigned Host can decide',()=>{const f=fixture();const r=f.service.request(f.input);f.role('Host','student-services');assert.throws(()=>f.service.decide(r.id,'approved'),/another host/);f.role('Host');assert.equal(f.service.decide(r.id,'approved').status,'approved');});
test('host list only contains assigned requests',()=>{const f=fixture();f.service.request(f.input);f.service.request({...f.input,host:'student-services'});f.role('Host');assert.equal(f.service.listForHost().length,1);f.role('Visitor');assert.throws(()=>f.service.listForHost());});
test('approval makes an unpredictable format-valid code',()=>{const f=fixture();const r=f.service.request(f.input);f.role('Host');assert.match(f.service.decide(r.id,'approved').code,/^[A-HJ-NP-Z2-9]{12}$/);});
test('denied requests have no code',()=>{const f=fixture();const r=f.service.request(f.input);f.role('Host');const d=f.service.decide(r.id,'denied');assert.equal(d.status,'denied');assert.equal(d.code,null);});
test('decisions cannot be repeated',()=>{const f=fixture();const r=f.service.request(f.input);f.role('Host');f.service.decide(r.id,'approved');assert.throws(()=>f.service.decide(r.id,'denied'),/already/);});
test('guard validates only approved same-day passes and exposes no name',()=>{const f=fixture();const r=f.service.request(f.input);f.role('Host');const approved=f.service.decide(r.id,'approved');f.role('Guard');const result=f.service.verify(' '+approved.code.toLowerCase()+' ');assert.equal(result.valid,true);assert.deepEqual(Object.keys(result).sort(),['date','valid']);f.date('2026-10-04');assert.equal(f.service.verify(approved.code).valid,false);});
test('a future visit cannot enter today',()=>{const f=fixture();const r=f.service.request({...f.input,date:'2026-10-04'});f.role('Host');const approved=f.service.decide(r.id,'approved');f.role('Guard');assert.equal(f.service.verify(approved.code).valid,false);});
test('pending requests and malformed codes are invalid',()=>{const f=fixture();f.service.request(f.input);f.role('Guard');for(const code of ['',null,'ABCDEFGHJKLM','<script>'])assert.equal(f.service.verify(code).valid,false);});
test('Visitor cannot call Guard verification',()=>{const f=fixture();assert.throws(()=>f.service.verify('ABCDEFGHJKLM'),/only Guard/);});
test('audit events omit visitor personal data and pass codes',()=>{const f=fixture();const r=f.service.request(f.input);f.role('Host');const d=f.service.decide(r.id,'approved');const serialized=JSON.stringify(f.events);assert(!serialized.includes('Alex Morgan'));assert(!serialized.includes(d.code));assert(serialized.includes('request-approved'));});
test('repository returns copies rather than live mutable records',()=>{const f=fixture();const r=f.service.request(f.input);r.status='approved';const got=f.repository.get(r.id);got.status='denied';assert.equal(f.repository.get(r.id).status,'pending');});
test('code collision cannot grant a second request the same code',()=>{const f=fixture({code:()=> 'ABCDEFGHJKLM'});const a=f.service.request(f.input);const b=f.service.request({...f.input,name:'Jamie Smith'});f.role('Host');f.service.decide(a.id,'approved');assert.throws(()=>f.service.decide(b.id,'approved'),/unique/);assert.equal(f.repository.get(b.id).status,'pending');});
